### ISSUE TITLE
Support for SHA256

### ISSUE THREAD

**Issue by jonallured** [derekparker/go-pear#5]
Heyo! Homebrew has deprecated support for SHA1 in Formulae, but for some reason they did it in such a way that actually blocks the install. :\

That means pear can't be installed until the Formula is updated to SHA256. If I have some time, I'll try to get a PR in for this, but wanted to open an issue in case someone else has the time to fix it.

Thanks!

**Comment by derekparker** [comment]
Totally should be updated, but I'm going to close out this issue, we should instead open an issue against: https://github.com/hashrocket/homebrew-formulas and update the SHA in the formula.

**Comment by jonallured** [comment]
Oh, right - thanks! 💋
